"""5-Day Plan — Linux & Docker through deploying AI-SOC Watchdog on AWS"""
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()
s = doc.styles['Normal']
s.font.name = 'Calibri'; s.font.size = Pt(11)
s.paragraph_format.line_spacing = 1.15; s.paragraph_format.space_after = Pt(4)
for l in range(1,4):
    h = doc.styles[f'Heading {l}']
    h.font.name = 'Calibri'; h.font.color.rgb = RGBColor(0x1a,0x1a,0x2e)

def bb(b,n):
    p=doc.add_paragraph(); r=p.add_run(b); r.bold=True; p.add_run(n); return p
def bul(t,bp=None):
    p=doc.add_paragraph(style='List Bullet')
    if bp: r=p.add_run(bp); r.bold=True; p.add_run(t)
    else: p.add_run(t)
    return p
def red(t):
    p=doc.add_paragraph(); r=p.add_run(t); r.bold=True; r.font.color.rgb=RGBColor(0xCC,0,0)
def grn(t):
    p=doc.add_paragraph(); r=p.add_run(t); r.bold=True; r.font.color.rgb=RGBColor(0,0x7A,0x33)
def blu(t):
    p=doc.add_paragraph(); r=p.add_run(t); r.bold=True; r.font.color.rgb=RGBColor(0x0d,0x47,0xa1)
def cd(t):
    p=doc.add_paragraph(); r=p.add_run(t); r.font.name='Consolas'; r.font.size=Pt(9)
    r.font.color.rgb=RGBColor(0x33,0x33,0x33); p.paragraph_format.left_indent=Inches(0.3)
def ital(t):
    p=doc.add_paragraph(); r=p.add_run(t); r.italic=True

# TITLE
doc.add_paragraph(); doc.add_paragraph()
t=doc.add_heading('5-Day Plan: Deploy AI-SOC Watchdog on AWS',level=0)
t.alignment=WD_ALIGN_PARAGRAPH.CENTER
p=doc.add_paragraph('Learn Linux + Docker + Terraform by actually deploying your project')
p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.runs[0].font.size=Pt(14); p.runs[0].font.color.rgb=RGBColor(0x55,0x55,0x55)
doc.add_page_break()

# OVERVIEW
doc.add_heading('The Idea',level=1)
bb('Problem: ','Practicing Linux and Docker separately feels disconnected from your resume.')
bb('Solution: ','Every concept is practiced IN THE CONTEXT of deploying AI-SOC Watchdog to AWS.')
doc.add_paragraph()
bb('Resume claim: ','"Containerized the full stack with Docker Compose... Deployed on AWS using Terraform... S3 fallback... env vars + auth"')
doc.add_paragraph()
bb('By Day 5 you\'ll have: ','An EC2 instance you set up with Linux skills, running your Dockerized project, with iptables firewall, SSH hardening, and Terraform IaC — matching every resume bullet.')

doc.add_heading('Daily Flow',level=2)
bul('Launch EC2 → Linux basics: users, groups, permissions for the project directories','Day 1: ')
bul('systemd service for the app + cron backups + LVM storage + log analysis','Day 2: ')
bul('iptables firewall + SSH hardening on the EC2 instance','Day 3: ')
bul('Dockerize AI-SOC Watchdog — Dockerfile + volumes + networks','Day 4: ')
bul('Docker Compose full stack + Terraform IaC + S3 failover + CI/CD knowledge','Day 5: ')

doc.add_paragraph()
grn('Every concept ties directly to a resume claim. Nothing wasted.')
doc.add_page_break()

# ============================================================================
# DAY 1
# ============================================================================
doc.add_heading('DAY 1: Launch EC2 + Linux Users/Groups/Permissions',level=1)
bb('Resume: ','"Built a Linux environment from scratch including... user management"')
bb('What you\'ll do: ','Launch an Ubuntu EC2, set up project users, groups, and directory permissions for AI-SOC Watchdog.')
doc.add_paragraph()

doc.add_heading('Block 1: Launch EC2 Instance (20 min)',level=2)
bul('Go to AWS Console → EC2 → Launch Instance')
bul('Ubuntu 22.04, t2.micro (free tier), 20GB storage')
bul('Create or select a key pair (.pem file)')
bul('Security group: allow SSH (22) from your IP only')
bul('Launch and connect:')
cd('ssh -i ~/your-key.pem ubuntu@<public-ip>')
doc.add_paragraph()
bb('Explore the filesystem — this is YOUR server now:','')
cd('ls /etc /var/log /opt /proc /tmp')
cd('cat /etc/os-release')
cd('cat /proc/cpuinfo | head -10')
cd('df -h')
doc.add_paragraph()
bb('Interview: ','"/etc = configs, /var/log = logs, /opt = third-party apps like our project, /proc = kernel info (virtual, not on disk)"')

doc.add_heading('Block 2: Create Project Users & Groups (25 min)',level=2)
bb('Context: ','Your app needs a service account (not root), and you need team-based access control.')
cd('# Service account for the app (cannot log in — security)')
cd('sudo useradd -r -s /usr/sbin/nologin soc-app')
cd('')
cd('# Human admin account')
cd('sudo useradd -m -s /bin/bash analyst')
cd('sudo passwd analyst')
cd('')
cd('# Team groups')
cd('sudo groupadd soc-team        # SOC analysts')
cd('sudo groupadd app-deploy      # Deployment access')
cd('')
cd('# Assign')
cd('sudo usermod -aG soc-team analyst')
cd('sudo usermod -aG app-deploy ubuntu    # Your SSH user')
cd('sudo usermod -aG app-deploy soc-app')
cd('sudo usermod -aG docker ubuntu        # For Docker later')
cd('')
cd('# Verify')
cd('id soc-app')
cd('id analyst')
cd('groups ubuntu')
cd('getent group soc-team')
cd('getent group app-deploy')
doc.add_paragraph()
bb('Interview answers:','')
bul('"useradd -r -s /usr/sbin/nologin creates a service account. It runs the app daemon but can\'t get an interactive shell — least privilege."','Q: Service account? ')
bul('"Without -a, usermod -G REPLACES all groups. The user loses everything except the new group. -a means APPEND. #1 Linux admin mistake."','Q: Why -a in usermod? ')

doc.add_heading('Block 3: Project Directory Permissions (30 min)',level=2)
bb('Context: ','Set up /opt/soc-watchdog with proper ownership and permissions — exactly what an architect would do.')
cd('# Create project structure')
cd('sudo mkdir -p /opt/soc-watchdog/{app,logs,backups,configs,data}')
cd('')
cd('# Ownership — app-deploy group owns app dirs')
cd('sudo chown -R root:app-deploy /opt/soc-watchdog/app')
cd('sudo chown -R root:app-deploy /opt/soc-watchdog/configs')
cd('sudo chown -R soc-app:app-deploy /opt/soc-watchdog/data')
cd('')
cd('# SOC team owns logs (analysts read logs, app writes logs)')
cd('sudo chown -R soc-app:soc-team /opt/soc-watchdog/logs')
cd('')
cd('# Permissions')
cd('sudo chmod 770 /opt/soc-watchdog/app        # Deploy team only')
cd('sudo chmod 2770 /opt/soc-watchdog/app       # SGID — new files inherit group')
cd('sudo chmod 770 /opt/soc-watchdog/configs    # Deploy team only')
cd('sudo chmod 750 /opt/soc-watchdog/logs       # SOC reads, app writes')
cd('sudo chmod 700 /opt/soc-watchdog/backups    # Root only')
cd('')
cd('# Test access control')
cd('sudo -u analyst ls /opt/soc-watchdog/logs     # WORKS (soc-team)')
cd('sudo -u analyst ls /opt/soc-watchdog/configs  # DENIED')
cd('sudo -u soc-app touch /opt/soc-watchdog/logs/app.log  # WORKS')
cd('')
cd('ls -la /opt/soc-watchdog/')
doc.add_paragraph()
bb('Interview answers:','')
bul('"770 = owner+group rwx, others nothing. I used group-based access so adding a new team member = just add them to the group."','Q: Explain your permissions? ')
bul('"SGID (2770) on a directory makes new files inherit the directory\'s group instead of the creator\'s group. Team members can edit each other\'s files."','Q: What\'s SGID? ')
bul('"Refuse. Diagnose who needs access, use group ownership + 770."','Q: chmod 777? ')
bul('"SUID = file runs as file OWNER. /usr/bin/passwd is SUID root so users can change passwords. Risk: unexpected SUID = privilege escalation. Audit: find / -perm -4000."','Q: SUID? ')
bul('"Sticky bit on /tmp: everyone can write, but only file owner can delete their own files."','Q: Sticky bit? ')

doc.add_paragraph()
bb('STAR:','')
ital('Situation: Deploying AI-SOC Watchdog on EC2 — needed separation between deployment, app runtime, and analyst access. Task: Least privilege for each role. Action: Created soc-app service account (no shell), soc-team and app-deploy groups, SGID on app directory for team collaboration, 750 on logs so analysts can read but not write. Result: Verified with sudo -u testing — analyst can\'t touch configs, app can\'t access backups. Clean separation.')

doc.add_paragraph()
bb('Day 1 checkpoint: ','You have an EC2 with users, groups, and a properly permissioned project directory. Concepts 1-4 done.')
doc.add_page_break()

# ============================================================================
# DAY 2
# ============================================================================
doc.add_heading('DAY 2: systemd + Cron + Logs + LVM for the Project',level=1)
bb('Resume: ','"Configured systemd services and cron jobs... used journalctl to diagnose failures" + "LVM volume configuration"')
doc.add_paragraph()

doc.add_heading('Block 1: systemd Service for AI-SOC Watchdog (35 min)',level=2)
bb('Context: ','Run your Flask app as a proper systemd service that auto-starts on boot and restarts on crash.')
cd('# Install project dependencies on EC2')
cd('sudo apt update && sudo apt install -y python3-pip python3-venv')
cd('')
cd('# Clone your project')
cd('cd /opt/soc-watchdog/app')
cd('sudo git clone https://github.com/karanam61/LLM-watchdog-prototype.git .')
cd('sudo chown -R soc-app:app-deploy /opt/soc-watchdog/app')
cd('')
cd('# Create venv and install deps')
cd('sudo -u soc-app python3 -m venv /opt/soc-watchdog/app/venv')
cd('sudo -u soc-app /opt/soc-watchdog/app/venv/bin/pip install -r requirements.txt')
cd('')
cd('# Create the systemd unit file')
cd('sudo tee /etc/systemd/system/soc-watchdog.service << \'UNIT\'')
cd('[Unit]')
cd('Description=AI-SOC Watchdog Backend')
cd('After=network.target')
cd('')
cd('[Service]')
cd('Type=simple')
cd('User=soc-app')
cd('Group=app-deploy')
cd('WorkingDirectory=/opt/soc-watchdog/app')
cd('EnvironmentFile=/opt/soc-watchdog/configs/.env')
cd('ExecStart=/opt/soc-watchdog/app/venv/bin/gunicorn -w 2 app:app --bind 0.0.0.0:5000 --timeout 120')
cd('Restart=on-failure')
cd('RestartSec=10')
cd('StandardOutput=journal')
cd('StandardError=journal')
cd('')
cd('# Security hardening')
cd('NoNewPrivileges=true')
cd('ProtectHome=true')
cd('PrivateTmp=true')
cd('')
cd('[Install]')
cd('WantedBy=multi-user.target')
cd('UNIT')
cd('')
cd('# Create .env file with secrets')
cd('sudo tee /opt/soc-watchdog/configs/.env << \'ENV\'')
cd('ANTHROPIC_API_KEY=your_key_here')
cd('SUPABASE_URL=your_url')
cd('SUPABASE_KEY=your_key')
cd('SESSION_SECRET=your_secret')
cd('ENV')
cd('sudo chmod 600 /opt/soc-watchdog/configs/.env    # Only root/service reads')
cd('')
cd('# Start')
cd('sudo systemctl daemon-reload')
cd('sudo systemctl enable --now soc-watchdog')
cd('sudo systemctl status soc-watchdog')
cd('sudo journalctl -u soc-watchdog -n 20')
cd('curl http://localhost:5000/api/health')
doc.add_paragraph()
bb('Interview:','')
bul('"daemon-reload re-reads unit files. enable = start on boot. start = run now. enable --now = both."','Q: enable vs start? ')
bul('"systemctl status for state + last lines. journalctl -u service -n 50 for detail. Exit 137=OOM, 1=app error."','Q: Service crashing? ')
bul('"EnvironmentFile in the unit file points to a .env with chmod 600. Secrets never in the unit file itself."','Q: How do you pass secrets to systemd? ')

doc.add_heading('Block 2: Cron Backup Job (15 min)',level=2)
cd('# Backup script for the project')
cd('sudo tee /opt/soc-watchdog/backups/backup.sh << \'SCRIPT\'')
cd('#!/bin/bash')
cd('DATE=$(date +%Y%m%d-%H%M)')
cd('tar -czf /opt/soc-watchdog/backups/config-$DATE.tar.gz /opt/soc-watchdog/configs/ 2>/dev/null')
cd('tar -czf /opt/soc-watchdog/backups/chromadb-$DATE.tar.gz /opt/soc-watchdog/app/backend/chromadb_data/ 2>/dev/null')
cd('find /opt/soc-watchdog/backups -name "*.tar.gz" -mtime +7 -delete')
cd('echo "$(date) Backup complete" >> /opt/soc-watchdog/backups/backup.log')
cd('SCRIPT')
cd('sudo chmod +x /opt/soc-watchdog/backups/backup.sh')
cd('')
cd('# Schedule: daily at 2 AM')
cd('(sudo crontab -l 2>/dev/null; echo "0 2 * * * /opt/soc-watchdog/backups/backup.sh") | sudo crontab -')
cd('sudo crontab -l')
cd('')
cd('# Test manually')
cd('sudo /opt/soc-watchdog/backups/backup.sh')
cd('ls -la /opt/soc-watchdog/backups/')
doc.add_paragraph()
bb('Interview: ','"0 2 * * * = daily at 2AM. I backup both configs (.env) and the ChromaDB vector data. Clean backups older than 7 days."')

doc.add_heading('Block 3: Log Analysis — Diagnose Your App (20 min)',level=2)
cd('# Your app\'s logs via journalctl')
cd('journalctl -u soc-watchdog -n 20')
cd('journalctl -u soc-watchdog --since "10 min ago"')
cd('journalctl -u soc-watchdog -f                   # Follow live')
cd('journalctl -u soc-watchdog -p err                # Errors only')
cd('')
cd('# System-wide analysis')
cd('journalctl --since "1 hour ago" -p err')
cd('journalctl -u ssh | grep "Failed password" | tail -5')
cd('')
cd('# SOC pattern — top failed SSH IPs')
cd('journalctl -u ssh --since today | grep "Failed password" | \\')
cd('  grep -oP "\\d+\\.\\d+\\.\\d+\\.\\d+" | sort | uniq -c | sort -rn | head -5')
doc.add_paragraph()
bb('Interview: ','"journalctl -u soc-watchdog -p err --since 1h ago shows my app\'s recent errors. For SSH brute-force: grep Failed password, extract IPs with sort+uniq, check grep Accepted for successful breach."')

doc.add_heading('Block 4: fdisk + LVM Storage for Logs (30 min)',level=2)
bb('Context: ','Attach an extra EBS volume to EC2. First partition it with fdisk, then use LVM on top.')
cd('# Add a 5GB EBS volume in AWS Console → attach to instance')
cd('lsblk                        # See all disks — new one is probably /dev/xvdf')
cd('sudo fdisk -l /dev/xvdf      # Confirm it\'s the right disk')
cd('')
cd('# Partition with fdisk')
cd('sudo fdisk /dev/xvdf')
cd('# Inside fdisk:')
cd('#   n → new partition')
cd('#   p → primary')
cd('#   1 → partition 1')
cd('#   [Enter] → default first sector')
cd('#   [Enter] → use entire disk')
cd('#   p → print table (verify)')
cd('#   w → WRITE to disk')
cd('')
cd('lsblk                        # Now shows xvdf1')
cd('')
cd('# Option A: Simple filesystem (no LVM)')
cd('sudo mkfs.ext4 /dev/xvdf1')
cd('sudo mkdir -p /mnt/simple-test')
cd('sudo mount /dev/xvdf1 /mnt/simple-test')
cd('df -h /mnt/simple-test       # Works! But fixed size.')
cd('sudo umount /mnt/simple-test')
cd('')
cd('# Option B: LVM on top of partition (flexible — use this)')
cd('sudo wipefs -a /dev/xvdf1    # Clear filesystem for LVM')
cd('')
cd('# LVM hierarchy: PV → VG → LV → filesystem → mount')
cd('sudo pvcreate /dev/xvdf                          # New EBS volume')
cd('sudo vgcreate vg_soc /dev/xvdf')
cd('sudo lvcreate -L 3G -n lv_logs vg_soc')
cd('sudo mkfs.ext4 /dev/vg_soc/lv_logs')
cd('')
cd('# Mount for project logs')
cd('sudo mount /dev/vg_soc/lv_logs /opt/soc-watchdog/logs')
cd('df -h /opt/soc-watchdog/logs')
cd('')
cd('# THE KEY SKILL — live expansion (no downtime)')
cd('sudo lvextend -L +1G /dev/vg_soc/lv_logs')
cd('sudo resize2fs /dev/vg_soc/lv_logs')
cd('df -h /opt/soc-watchdog/logs    # Now 4GB!')
cd('')
cd('# Persist in fstab')
cd('sudo cp /etc/fstab /etc/fstab.backup')
cd('echo "/dev/vg_soc/lv_logs /opt/soc-watchdog/logs ext4 defaults,noexec,nosuid 0 2" | sudo tee -a /etc/fstab')
cd('sudo mount -a    # Test')
doc.add_paragraph()
bb('Interview:','')
bul('"fdisk creates fixed partitions on a disk — n for new, p for primary, w to write. Limitation: partitions are fixed size. That\'s why I use LVM on top — it adds flexibility."','Q: What does fdisk do? ')
bul('"lvextend +5G then resize2fs — done live, zero downtime. If VG is full, pvcreate a new disk, vgextend, then lvextend."','Q: /var/log full on LVM? ')
bul('"noexec prevents executing binaries from that mount. Even if attacker writes malware to logs, kernel won\'t run it."','Q: Why noexec? ')

doc.add_paragraph()
bb('Day 2 checkpoint: ','Your app runs as a systemd service, has cron backups, logs are queryable via journalctl, and storage is on LVM. Concepts 5-10 done.')
doc.add_page_break()

# ============================================================================
# DAY 3
# ============================================================================
doc.add_heading('DAY 3: Firewall + SSH — Secure the EC2 Instance',level=1)
bb('Resume: ','"Configured iptables firewall rules... verified with live traffic" + "Added request validation and authentication before exposing the service publicly"')
doc.add_paragraph()

doc.add_heading('Block 1: iptables Firewall (50 min)',level=2)
bb('Context: ','Your EC2 runs the Watchdog API on port 5000. Lock down everything except what\'s needed.')
cd('# Flush and start clean')
cd('sudo iptables -F && sudo iptables -X')
cd('')
cd('# DEFAULT DENY')
cd('sudo iptables -P INPUT DROP')
cd('sudo iptables -P FORWARD DROP')
cd('sudo iptables -P OUTPUT ACCEPT')
cd('')
cd('# Allow loopback')
cd('sudo iptables -A INPUT -i lo -j ACCEPT')
cd('')
cd('# Allow established connections (responses to our requests)')
cd('sudo iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT')
cd('')
cd('# SSH with rate limiting (brute-force defense)')
cd('sudo iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --set --name SSH')
cd('sudo iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 4 --name SSH -j LOG --log-prefix "SSH-BRUTE: "')
cd('sudo iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 4 --name SSH -j DROP')
cd('sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT')
cd('')
cd('# Allow HTTP/HTTPS (for the app)')
cd('sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT')
cd('sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT')
cd('')
cd('# Allow app port (5000) — or restrict to ALB/specific IPs')
cd('sudo iptables -A INPUT -p tcp --dport 5000 -j ACCEPT')
cd('')
cd('# Allow ping')
cd('sudo iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT')
cd('')
cd('# Log everything else')
cd('sudo iptables -A INPUT -j LOG --log-prefix "DROPPED: " --log-level 4')
cd('')
cd('# Verify')
cd('sudo iptables -L -n -v --line-numbers')
cd('')
cd('# TEST WITH LIVE TRAFFIC (as resume claims)')
cd('curl http://localhost:5000/api/health            # WORKS (port 5000 allowed)')
cd('curl http://localhost:8080 2>&1                   # DROPPED (not whitelisted)')
cd('sudo journalctl -k | grep "DROPPED"              # See blocked traffic')
cd('sudo journalctl -k | grep "SSH-BRUTE"            # See brute-force blocks')
cd('')
cd('# Persist')
cd('sudo apt install -y iptables-persistent')
cd('sudo netfilter-persistent save')
doc.add_paragraph()
bb('Interview:','')
bul('"Default DROP on INPUT. Whitelist: loopback, ESTABLISHED/RELATED, SSH with rate limiting (3/60s), HTTP/HTTPS, app port, ICMP. Log before implicit drop."','Q: Walk through your firewall? ')
bul('"Without it, DNS replies and apt updates get dropped. It allows responses to OUR outbound connections."','Q: ESTABLISHED,RELATED? ')
bul('"recent module tracks per-IP connections. >3 new SSH in 60s → LOG + DROP. I verified it works by checking journalctl for SSH-BRUTE entries."','Q: Rate limiting? ')

doc.add_heading('Block 2: SSH Hardening (35 min)',level=2)
cd('# Generate ed25519 key (if not using AWS .pem)')
cd('ssh-keygen -t ed25519 -C "soc-deploy" -f ~/.ssh/soc_key')
cd('ssh-copy-id -i ~/.ssh/soc_key.pub ubuntu@<ec2-ip>')
cd('ssh -i ~/.ssh/soc_key ubuntu@<ec2-ip> whoami    # No password!')
cd('')
cd('# Harden SSH on the EC2')
cd('sudo tee /etc/ssh/sshd_config.d/hardening.conf << \'SSH\'')
cd('PasswordAuthentication no')
cd('PermitRootLogin no')
cd('MaxAuthTries 3')
cd('PermitEmptyPasswords no')
cd('ClientAliveInterval 300')
cd('ClientAliveCountMax 2')
cd('X11Forwarding no')
cd('LogLevel VERBOSE')
cd('SSH')
cd('')
cd('sudo sshd -t                # Validate config')
cd('sudo systemctl restart sshd')
cd('sudo sshd -T | grep -E "passwordauthentication|permitrootlogin"')
cd('')
cd('# SCP — deploy config files to EC2')
cd('scp -i ~/.ssh/soc_key .env ubuntu@<ec2-ip>:/opt/soc-watchdog/configs/')
doc.add_paragraph()
bb('Interview:','')
bul('"Private key never crosses the network. Can\'t be brute-forced or phished. With PasswordAuthentication no, password attacks are structurally impossible."','Q: Why keys > passwords? ')
bul('"Forces named accounts + sudo = audit trail. I see who did what."','Q: PermitRootLogin no? ')

bb('STAR:','')
ital('Situation: EC2 running AI-SOC Watchdog publicly. Task: Minimize attack surface. Action: iptables default-deny, whitelisted only SSH/HTTP/5000, rate-limited SSH to 3/min, ed25519 key auth, disabled passwords, PermitRootLogin no. Result: Verified — rapid SSH attempts get blocked and logged. Dropped traffic visible in journalctl. Zero password-based attack surface.')

bb('Day 3 checkpoint: ','EC2 is hardened with firewall + SSH. Concepts 11-16 done.')
doc.add_page_break()

# ============================================================================
# DAY 4
# ============================================================================
doc.add_heading('DAY 4: Dockerize AI-SOC Watchdog',level=1)
bb('Resume: ','"Containerized the full stack with Docker... each service in its own container"')
doc.add_paragraph()

doc.add_heading('Block 1: Dockerfile for the Backend (35 min)',level=2)
bb('Context: ','Create a production Dockerfile for your Flask backend.')
cd('# On your local machine (or EC2)')
cd('cd /opt/soc-watchdog/app    # or your local project directory')
cd('')
cd('cat > Dockerfile << \'DF\'')
cd('FROM python:3.11-slim')
cd('')
cd('WORKDIR /app')
cd('')
cd('# Layer caching: requirements first (changes less often)')
cd('COPY requirements.txt .')
cd('RUN pip install --no-cache-dir -r requirements.txt')
cd('')
cd('# Copy application code')
cd('COPY . .')
cd('')
cd('# Non-root user (security)')
cd('RUN useradd -r -s /usr/sbin/nologin appuser')
cd('USER appuser')
cd('')
cd('EXPOSE 5000')
cd('')
cd('ENTRYPOINT ["gunicorn", "-w", "2", "app:app", "--bind", "0.0.0.0:5000", "--timeout", "120"]')
cd('DF')
cd('')
cd('# Build')
cd('docker build -t soc-watchdog:v1 .')
cd('docker images soc-watchdog')
cd('docker history soc-watchdog:v1    # See layers')
cd('')
cd('# Run')
cd('docker run -d --name watchdog -p 5000:5000 \\')
cd('  -e ANTHROPIC_API_KEY=your_key \\')
cd('  -e SUPABASE_URL=your_url \\')
cd('  soc-watchdog:v1')
cd('')
cd('curl http://localhost:5000/api/health')
cd('docker logs watchdog')
doc.add_paragraph()
bb('Key points — know cold:','')
bul('COPY requirements first → pip install → COPY code = layer cache optimization','')
bul('USER appuser = never run as root in container','')
bul('ENTRYPOINT = gunicorn (production server), not Flask dev server','')
bul('ENTRYPOINT = fixed command. CMD = overridable defaults. COPY > ADD.','')

doc.add_heading('Block 2: Container Lifecycle (25 min)',level=2)
cd('docker ps                              # Running')
cd('docker ps -a                           # All (including stopped)')
cd('docker logs watchdog --tail 20         # Last 20 lines')
cd('docker logs -f watchdog                # Follow live')
cd('docker exec watchdog cat /etc/os-release')
cd('docker exec -it watchdog /bin/bash     # Shell inside')
cd('docker stats watchdog                  # CPU/memory')
cd('docker inspect watchdog | grep -i ipaddress')
cd('')
cd('docker stop watchdog')
cd('docker start watchdog')
cd('docker restart watchdog')
cd('docker stop watchdog && docker rm watchdog')
doc.add_paragraph()
bb('Interview: ','"docker logs for output, docker ps -a for exit code (137=OOM, 1=app error), docker exec -it for interactive debug."')

doc.add_heading('Block 3: Volumes + Networks (30 min)',level=2)
bb('Context: ','ChromaDB data must persist. Backend and frontend need networking.')
cd('# Named volume for ChromaDB (RAG knowledge base)')
cd('docker volume create chromadb-data')
cd('docker volume create app-logs')
cd('')
cd('docker run -d --name watchdog -p 5000:5000 \\')
cd('  -v chromadb-data:/app/backend/chromadb_data \\')
cd('  -v app-logs:/app/logs \\')
cd('  --env-file .env \\')
cd('  soc-watchdog:v1')
cd('')
cd('# Kill and recreate — data survives!')
cd('docker rm -f watchdog')
cd('docker volume ls    # Volumes still exist')
cd('')
cd('# Custom network')
cd('docker network create soc-network')
cd('docker run -d --name watchdog --network soc-network -p 5000:5000 soc-watchdog:v1')
cd('docker run --rm --network soc-network alpine ping -c 2 watchdog    # DNS works!')
cd('')
cd('# Isolation test')
cd('docker network create isolated')
cd('docker run -d --name other --network isolated alpine sleep infinity')
cd('docker exec other ping -c 2 watchdog 2>&1    # FAILS — different networks')
cd('')
cd('docker rm -f watchdog other')
cd('docker network rm soc-network isolated')
doc.add_paragraph()
bb('Interview:','')
bul('"Named volumes for ChromaDB — the RAG knowledge base must survive container restarts. Bind mounts for .env configs. Volumes = Docker-managed, bind mounts = host-controlled."','Q: How do you persist data? ')
bul('"Custom bridge gives DNS — containers find each other by name. Default bridge = IP only."','Q: Custom network why? ')

bb('Day 4 checkpoint: ','Your project runs in Docker with persistent volumes and custom networking. Concepts 17-20 done.')
doc.add_page_break()

# ============================================================================
# DAY 5
# ============================================================================
doc.add_heading('DAY 5: Docker Compose + Terraform + CI/CD',level=1)
bb('Resume: ','"Docker Compose with each service in its own container" + "Deployed on AWS using Terraform" + "S3 fallback" + "env vars + auth"')
doc.add_paragraph()

doc.add_heading('Block 1: Docker Compose for AI-SOC Watchdog (45 min)',level=2)
cd('cat > docker-compose.yml << \'YML\'')
cd('version: "3.8"')
cd('services:')
cd('  nginx:')
cd('    image: nginx:alpine')
cd('    container_name: soc-proxy')
cd('    ports: ["80:80"]')
cd('    volumes:')
cd('      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro')
cd('    networks: [frontend]')
cd('    depends_on: [backend]')
cd('    restart: unless-stopped')
cd('')
cd('  backend:')
cd('    build: .')
cd('    container_name: soc-backend')
cd('    env_file: .env')
cd('    volumes:')
cd('      - chromadb-data:/app/backend/chromadb_data')
cd('      - app-logs:/app/logs')
cd('    networks: [frontend, backend]')
cd('    depends_on: [redis]')
cd('    restart: unless-stopped')
cd('')
cd('  redis:')
cd('    image: redis:7-alpine')
cd('    container_name: soc-cache')
cd('    command: redis-server --appendonly yes')
cd('    volumes:')
cd('      - redis-data:/data')
cd('    networks: [backend]')
cd('    restart: unless-stopped')
cd('')
cd('networks:')
cd('  frontend:')
cd('  backend:')
cd('    internal: true    # Redis completely isolated from outside')
cd('')
cd('volumes:')
cd('  chromadb-data:')
cd('  app-logs:')
cd('  redis-data:')
cd('YML')
cd('')
cd('# Nginx config')
cd('cat > nginx.conf << \'CONF\'')
cd('upstream api { server soc-backend:5000; }')
cd('server {')
cd('    listen 80;')
cd('    location / { proxy_pass http://api; proxy_set_header Host $host; }')
cd('}')
cd('CONF')
cd('')
cd('# Launch')
cd('docker compose up -d --build')
cd('docker compose ps')
cd('curl http://localhost/api/health')
cd('')
cd('# VERIFY NETWORK ISOLATION')
cd('docker exec soc-proxy ping -c 2 soc-cache 2>&1    # FAILS!')
cd('docker exec soc-backend ping -c 2 soc-cache        # WORKS')
cd('')
cd('# VERIFY PERSISTENCE')
cd('docker compose down && docker compose up -d')
cd('docker volume ls | grep chromadb    # Data survived')
cd('')
cd('docker compose logs -f backend')
cd('docker compose down')
doc.add_paragraph()
bb('Interview:','')
bul('"3 services: nginx (reverse proxy), Flask backend, Redis cache. Frontend+backend networks with internal:true on backend — Redis is completely unreachable from outside."','Q: Describe your Compose? ')
bul('"down keeps volumes. down -v DELETES volumes = data loss. Never -v in production."','Q: down vs down -v? ')
bul('"Startup order only, not readiness. Redis container starts but may still be initializing. Use healthchecks for true readiness."','Q: depends_on limitation? ')

doc.add_heading('Block 2: Terraform + S3 Failover (30 min READ)',level=2)
bb('Your resume says Terraform + S3 fallback. Know these cold:','')
doc.add_paragraph()

blu('Terraform — what you\'d write:')
bul('VPC with public + private subnets')
bul('EC2 instance (or ECS) for the backend container')
bul('S3 bucket for database failover')
bul('Security group: SSH (22), HTTP (80), app (5000)')
bul('IAM role for EC2 → S3 access')
bul('RDS PostgreSQL (if replacing Supabase)')
cd('')
cd('# Terraform workflow')
cd('terraform init      # Download providers')
cd('terraform plan      # Preview changes')
cd('terraform apply     # Create resources')
cd('terraform destroy   # Tear down everything')
doc.add_paragraph()
bb('Interview: ','"I wrote Terraform to provision a VPC, EC2, security group, S3 bucket, and IAM role. terraform apply creates it, terraform destroy tears it down. Everything is version-controlled so the environment is reproducible."')

doc.add_paragraph()
blu('S3 Failover — you already built this:')
bul('Normal: reads/writes → Supabase, background sync to S3 every 5 min')
bul('Failover: after 3 consecutive DB failures, reads fall back to S3')
bul('Recovery: auto-exits failover when Supabase comes back')
bul('Limitation: writes during failover need manual reconciliation')
bb('Interview: ','"I configured S3 as a database fallback using boto3. The system detects 3 consecutive Supabase failures, switches to reading from S3, and auto-recovers. This ensures the app stays available during DB outages."')

doc.add_paragraph()
blu('Environment Variables + Auth — you already built this:')
bul('All secrets in .env (ANTHROPIC_API_KEY, SUPABASE_KEY, SESSION_SECRET)')
bul('python-dotenv loads them; .gitignore prevents commit')
bul('Request validation: Pydantic schemas on all inputs')
bul('Auth: session-based login, secrets.compare_digest() (timing-safe)')
bul('Security: 2MB request limit, secure cookies, header redaction in logs')

doc.add_heading('Block 3: JD Concepts — K8s, CI/CD, Service Mesh (20 min READ)',level=2)

blu('Kubernetes / EKS:')
bul('"My Docker Compose works for one server. K8s scales to multiple servers with auto-scaling, rolling updates, and self-healing. EKS is AWS-managed K8s."','One-liner: ')
bul('Pod = 1+ containers. Deployment = manages replicas. Service = stable endpoint. Ingress = external entry.','Key concepts: ')

doc.add_paragraph()
blu('CI/CD (GitHub Actions):')
bul('"Push to main → GitHub Actions runs tests → builds Docker image → pushes to registry → deploys → health check. Staging branch → staging, main → production."','One-liner: ')

doc.add_paragraph()
blu('Service Mesh (Istio):')
bul('"Sidecar proxies added to every pod. Handles mTLS, traffic routing, retries, observability between microservices. I understand the concept but haven\'t implemented it."','One-liner: ')

doc.add_paragraph()
doc.add_paragraph()
bb('Day 5 checkpoint: ','Full stack running in Docker Compose. Can explain Terraform, S3 failover, CI/CD, and K8s. Concepts 21-25 done + all resume claims covered.')

doc.add_page_break()

# ============================================================================
# CHEAT SHEET
# ============================================================================
doc.add_heading('Cheat Sheet — Print This',level=1)

doc.add_heading('Linux',level=2)
cd('useradd -m -s /bin/bash USER          # Human user')
cd('useradd -r -s /usr/sbin/nologin SVC   # Service account')
cd('usermod -aG GROUP USER                # ALWAYS -a to append')
cd('chmod 770 DIR / chmod 2770 DIR        # Team / SGID')
cd('systemctl enable --now SERVICE        # Start + boot')
cd('journalctl -u SERVICE -p err          # Service errors')
cd('pvcreate→vgcreate→lvcreate→mkfs→mount # LVM')
cd('lvextend -L +5G LV && resize2fs LV   # Live expand')
cd('iptables -P INPUT DROP               # Default deny')
cd('ssh-keygen -t ed25519                 # Key auth')

doc.add_heading('Docker',level=2)
cd('docker build -t name:tag .            # Build')
cd('docker run -d --name X -p 80:80 IMG   # Run')
cd('docker ps / logs / exec / stop / rm   # Lifecycle')
cd('docker volume create / network create # Persistence + DNS')

doc.add_heading('Docker Compose',level=2)
cd('docker compose up -d --build          # Start stack')
cd('docker compose ps / logs / down       # Manage')
cd('internal: true                        # Network isolation')

doc.add_heading('AWS/Terraform/JD',level=2)
cd('terraform init → plan → apply → destroy')
cd('K8s: Pod → Deployment → Service → Ingress')
cd('CI/CD: push → test → build → push → deploy → health check')

doc.add_page_break()

# SCHEDULE
doc.add_heading('Exact Schedule (2 hrs/day)',level=1)
doc.add_heading('Day 1 — EC2 + Users/Groups/Permissions',level=2)
bul('Launch EC2, SSH in, explore filesystem','0:00-0:20 → ')
bul('Create soc-app, analyst users + soc-team, app-deploy groups','0:20-0:45 → ')
bul('Create /opt/soc-watchdog directories with proper ownership + permissions','0:45-1:15 → ')
bul('Test access control with sudo -u, memorize SUID/SGID/sticky answers','1:15-1:45 → ')
bul('Practice STAR answer out loud','1:45-2:00 → ')

doc.add_heading('Day 2 — systemd + Cron + Logs + LVM',level=2)
bul('Create systemd unit file for soc-watchdog, start the app as a service','0:00-0:35 → ')
bul('Create cron backup job for configs + ChromaDB','0:35-0:50 → ')
bul('Log analysis with journalctl — diagnose your app + SSH patterns','0:50-1:10 → ')
bul('LVM: create volume, mount for logs, live-expand, configure fstab','1:10-1:40 → ')
bul('Review: explain systemd, cron, LVM without notes','1:40-2:00 → ')

doc.add_heading('Day 3 — iptables + SSH Security',level=2)
bul('Build iptables firewall: default deny, whitelist SSH/HTTP/5000','0:00-0:40 → ')
bul('Add SSH rate limiting, test with live traffic, check logs','0:40-1:00 → ')
bul('SSH: generate keys, deploy, harden sshd_config','1:00-1:30 → ')
bul('SCP deploy .env to EC2, verify hardening','1:30-1:50 → ')
bul('Practice STAR answer out loud','1:50-2:00 → ')

doc.add_heading('Day 4 — Dockerize the Project',level=2)
bul('Write Dockerfile for AI-SOC Watchdog, build, run','0:00-0:35 → ')
bul('Container lifecycle: ps, logs, exec, stats, stop, rm','0:35-0:55 → ')
bul('Volumes for ChromaDB + logs, prove persistence across rm','0:55-1:15 → ')
bul('Custom networks, prove DNS + isolation','1:15-1:35 → ')
bul('Review: explain Dockerfile line by line, volumes vs bind mounts','1:35-2:00 → ')

doc.add_heading('Day 5 — Compose + Terraform + JD',level=2)
bul('Docker Compose: 3-service stack, verify network isolation + persistence','0:00-0:45 → ')
bul('Read: Terraform flow, S3 failover, env vars — memorize interview answers','0:45-1:15 → ')
bul('Read: K8s, CI/CD, service mesh one-liners','1:15-1:40 → ')
bul('FINAL TEST: 5 random concepts explained in 30s, 2 STAR answers out loud','1:40-2:00 → ')

doc.add_paragraph()
grn('After Day 5: Every resume bullet has hands-on proof. You deployed YOUR project, not some tutorial app. Go crush it.')

out = r'c:\Users\karan\Desktop\5Day_Linux_Docker_Plan.docx'
doc.save(out)
print(f"Done: {out}")
