"""Generate 5-Day Study Plan .docx"""
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

doc = Document()
style = doc.styles['Normal']
style.font.name = 'Calibri'
style.font.size = Pt(11)
style.paragraph_format.line_spacing = 1.15
style.paragraph_format.space_after = Pt(4)

for level in range(1, 4):
    hs = doc.styles[f'Heading {level}']
    hs.font.name = 'Calibri'
    hs.font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

def bold_body(bold_text, normal_text):
    p = doc.add_paragraph()
    r = p.add_run(bold_text)
    r.bold = True
    p.add_run(normal_text)
    return p

def bullet(text, bold_prefix=None):
    p = doc.add_paragraph(style='List Bullet')
    if bold_prefix:
        r = p.add_run(bold_prefix)
        r.bold = True
        p.add_run(text)
    else:
        p.add_run(text)
    return p

def red_text(text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = True
    r.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)
    return p

def green_text(text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = True
    r.font.color.rgb = RGBColor(0x00, 0x7A, 0x33)
    return p

def blue_label(text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = True
    r.font.color.rgb = RGBColor(0x0d, 0x47, 0xa1)
    return p

def code(text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.name = 'Consolas'
    r.font.size = Pt(9)
    r.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
    p.paragraph_format.left_indent = Inches(0.3)
    return p

# ============================================================================
# TITLE
# ============================================================================
doc.add_paragraph()
doc.add_paragraph()
title = doc.add_heading('5-Day Mastery Plan', level=0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
sub = doc.add_paragraph('Linux + Docker + Resume Projects — 2 Hours/Day')
sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
sub.runs[0].font.size = Pt(14)
sub.runs[0].font.color.rgb = RGBColor(0x55, 0x55, 0x55)
doc.add_paragraph()
tagline = doc.add_paragraph('Everything on your resume, practiced and interview-ready')
tagline.alignment = WD_ALIGN_PARAGRAPH.CENTER
tagline.runs[0].font.italic = True
doc.add_page_break()

# ============================================================================
# OVERVIEW
# ============================================================================
doc.add_heading('Plan Overview', level=1)

bold_body('Total time: ', '5 days × 2 hours = 10 hours')
bold_body('Goal: ', 'Be able to explain and demonstrate every claim on your resume')
doc.add_paragraph()

doc.add_heading('What You Claimed (Resume)', level=2)

blue_label('Linux and Docker Lab:')
bullet('Built a Linux environment from scratch — disk partitioning, LVM, filesystem mounts, user management')
bullet('Configured iptables firewall rules and verified with live traffic')
bullet('Used Docker Compose for multi-service apps — container networking + volume persistence')
bullet('Configured systemd services + cron jobs, used journalctl to diagnose failures')

doc.add_paragraph()
blue_label('AI Security Alert Tool:')
bullet('Containerized the full stack with Docker Compose — each service in its own container')
bullet('Deployed infrastructure on AWS using Terraform')
bullet('Configured S3 bucket as database fallback')
bullet('Stored API keys in environment variables, added request validation + authentication')

doc.add_paragraph()

doc.add_heading('What the JD Wants', level=2)
bullet('Kubernetes (EKS) — at least conceptual understanding')
bullet('CI/CD pipelines (GitHub Actions)')
bullet('Infrastructure-as-Code (Terraform)')
bullet('Containers and Kubernetes concepts')
bullet('Cloud concepts (compute, networking, storage)')
bullet('Foundational understanding, not expert — 0-3 years role')

doc.add_paragraph()
green_text('5 days is PLENTY. You\'ll be hands-on solid on everything you claimed.')

doc.add_heading('Daily Map', level=2)
bullet('Filesystem + Users + Groups + Permissions — Linux identity & access', 'Day 1: ')
bullet('systemd + Cron + Logs + LVM + fstab — Linux operations & storage', 'Day 2: ')
bullet('iptables + SSH — Linux security (matches resume claim)', 'Day 3: ')
bullet('Docker — Dockerfile + lifecycle + volumes + networks', 'Day 4: ')
bullet('Docker Compose + Containerizing the AI-SOC Watchdog + JD concepts (K8s, CI/CD, Terraform)', 'Day 5: ')

doc.add_page_break()

# ============================================================================
# DAY 1
# ============================================================================
doc.add_heading('DAY 1: Filesystem + Users + Groups + Permissions', level=1)
bold_body('Resume claim this proves: ', '"Built a Linux environment from scratch including... user management"')
doc.add_paragraph()

doc.add_heading('Block 1: Filesystem Hierarchy (15 min)', level=2)
bold_body('What: ', 'Linux organizes everything in a single tree from /. Each directory has a purpose.')
bold_body('Why it matters: ', 'Interviewers test this to see if you actually use Linux or just read about it.')
doc.add_paragraph()

bold_body('Do this:', '')
code('ls /etc/         # System config files')
code('ls /var/log/     # All log files')
code('ls /tmp/         # Temporary (cleared on reboot)')
code('ls /opt/         # Third-party software (Splunk, custom apps)')
code('ls /proc/        # Virtual — kernel/process info (not on disk)')
code('cat /etc/hostname')
code('cat /etc/os-release')
code('head -5 /etc/passwd')
code('cat /proc/cpuinfo | head -10')
code('df -h            # Disk usage per filesystem')

doc.add_paragraph()
bold_body('Memorize:', '')
bullet('/etc = configs, /var/log = logs, /tmp = scratch, /opt = third-party apps, /proc = kernel info')
bullet('"Where would Splunk live?" → /opt/splunk')
bullet('"Where are SSH configs?" → /etc/ssh/')

doc.add_paragraph()

doc.add_heading('Block 2: User Management (25 min)', level=2)
bold_body('What: ', 'Creating human users and service accounts. Every person and service gets their own account.')
doc.add_paragraph()

bold_body('Do this:', '')
code('# Human user')
code('sudo useradd -m -s /bin/bash alice')
code('sudo passwd alice')
code('id alice')
code('getent passwd alice')
code('')
code('# Service account (for daemons — cannot log in)')
code('sudo useradd -r -s /usr/sbin/nologin svc-monitor')
code('sudo su - svc-monitor    # Should say "not available"')
code('')
code('# Modify user — add to group')
code('sudo usermod -aG docker alice    # -a = APPEND (critical!)')
code('groups alice')
code('')
code('# Lock/unlock')
code('sudo usermod -L alice    # Lock')
code('sudo passwd -S alice     # Shows "L"')
code('sudo usermod -U alice    # Unlock')
code('')
code('# Delete')
code('sudo userdel -r alice    # -r removes home directory')

doc.add_paragraph()
bold_body('The /etc/passwd format — know cold:', '')
code('alice:x:1001:1001::/home/alice:/bin/bash')
code('│     │  │    │  │  │           └─ Shell')
code('│     │  │    │  │  └─ Home dir')
code('│     │  │    │  └─ Comment')
code('│     │  │    └─ Primary GID')
code('│     │  └─ UID')
code('│     └─ Password in /etc/shadow')
code('└─ Username')

doc.add_paragraph()
bold_body('Interview answers:', '')
bullet('"useradd -m -s /bin/bash -G docker username. -m creates home, -s sets shell, -G assigns groups."', 'Q: How do you create a user with Docker access? ')
bullet('"Without -a, usermod -G REPLACES all groups. Alice loses everything except docker. -a means APPEND. This is the #1 Linux admin mistake."', 'Q: What\'s -a in usermod? ')
bullet('"A service account runs daemons. /usr/sbin/nologin as shell means even with stolen credentials, no interactive session. Least privilege."', 'Q: What\'s a service account? ')

doc.add_paragraph()

doc.add_heading('Block 3: Group Management (15 min)', level=2)

bold_body('Do this:', '')
code('sudo groupadd soc-team')
code('sudo groupadd eng-team')
code('sudo groupadd company-all')
code('')
code('sudo useradd -m -s /bin/bash alice')
code('sudo useradd -m -s /bin/bash charlie')
code('sudo usermod -aG soc-team alice')
code('sudo usermod -aG eng-team charlie')
code('sudo usermod -aG company-all alice')
code('sudo usermod -aG company-all charlie')
code('')
code('getent group soc-team     # soc-team:x:1002:alice')
code('getent group eng-team     # eng-team:x:1003:charlie')
code('groups alice')

doc.add_paragraph()
bold_body('Interview:', '')
bullet('"Scalability. Adding a new analyst = add to soc-team, they inherit all access. No per-file permission hunting. Also auditable — getent group shows exactly who\'s in each role."', 'Q: Why groups instead of per-user permissions? ')

doc.add_paragraph()

doc.add_heading('Block 4: File Permissions — chmod, chown, SUID, SGID, Sticky (30 min)', level=2)

bold_body('Do this:', '')
code('# Create team directories')
code('sudo mkdir -p /opt/company/{app,logs,shared,configs}')
code('')
code('# Set ownership')
code('sudo chown root:eng-team /opt/company/app')
code('sudo chown root:soc-team /opt/company/logs')
code('sudo chown root:company-all /opt/company/shared')
code('')
code('# Set permissions (Read=4, Write=2, Execute=1)')
code('sudo chmod 770 /opt/company/app       # Owner+group full, others nothing')
code('sudo chmod 770 /opt/company/logs      # SOC only')
code('sudo chmod 775 /opt/company/shared    # Everyone reads, team writes')
code('')
code('# Test access control')
code('sudo -u alice touch /opt/company/logs/test.log    # WORKS (soc-team)')
code('sudo -u charlie touch /opt/company/logs/hack.txt  # DENIED (eng-team)')
code('sudo -u charlie touch /opt/company/app/code.py    # WORKS (eng-team)')
code('')
code('# SGID — new files inherit directory\'s group')
code('sudo chmod 2770 /opt/company/app')
code('ls -ld /opt/company/app    # drwxrws--- (s = SGID)')
code('sudo -u charlie touch /opt/company/app/feature.py')
code('ls -l /opt/company/app/feature.py    # Group = eng-team, not charlie')
code('')
code('# Sticky bit — only owner deletes own files')
code('ls -ld /tmp    # drwxrwxrwt (t = sticky)')
code('')
code('# Find all SUID binaries (security audit)')
code('find /usr -perm -4000 -type f 2>/dev/null')
code('')
code('# Permission cheat sheet:')
code('# 755 = rwxr-xr-x (scripts everyone runs)')
code('# 644 = rw-r--r-- (regular files)')
code('# 600 = rw------- (SSH keys, secrets)')
code('# 700 = rwx------ (private directories)')
code('# 770 = rwxrwx--- (team shared)')
code('# 2770 = rwxrws-- (team shared + SGID)')

doc.add_paragraph()
bold_body('Interview answers:', '')
bullet('"Refuse. 777 means every user can read, write, execute. Diagnose who actually needs access, use group ownership + 770."', 'Q: Someone says chmod 777? ')
bullet('"SUID = file executes as the file OWNER, not the runner. /usr/bin/passwd is SUID root — that\'s how users change passwords. Risk: unexpected SUID binaries = privilege escalation. Audit with find / -perm -4000."', 'Q: What\'s SUID? ')
bullet('"Without SGID, charlie\'s files are owned by charlie:charlie — dave can\'t edit. With SGID on the dir, new files inherit the directory\'s group (eng-team), so team members can collaborate."', 'Q: Explain SGID on a directory? ')

doc.add_paragraph()

bold_body('STAR answer for Day 1 — "Tell me about designing access control":', '')
p = doc.add_paragraph()
r = p.add_run('Situation: Building infrastructure for SOC and engineering teams needing different access. Task: Ensure separation — SOC reads logs but can\'t touch code, engineers deploy but can\'t access security data. Action: Created role-based groups (soc-team, eng-team), applied 770 for team isolation, SGID on shared directories for collaboration, service accounts with /usr/sbin/nologin. Result: Verified with sudo -u testing — charlie can\'t access /opt/company/logs, alice can\'t access /opt/company/app. Clean separation, auditable with getent group.')
r.italic = True

doc.add_page_break()

# ============================================================================
# DAY 2
# ============================================================================
doc.add_heading('DAY 2: systemd + Cron + Logs + LVM + fstab', level=1)
bold_body('Resume claims this proves: ', '"Configured systemd services and cron jobs for task automation and used journalctl to diagnose service failures" + "LVM volume configuration, filesystem mounts"')
doc.add_paragraph()

doc.add_heading('Block 1: systemd Services (35 min)', level=2)
bold_body('What: ', 'systemd manages daemons. You create unit files defining what to run, restart behavior, and dependencies.')
doc.add_paragraph()

bold_body('Do this:', '')
code('# Explore existing services')
code('systemctl list-units --type=service | head -20')
code('systemctl status ssh')
code('')
code('# Create a monitoring script')
code('sudo mkdir -p /opt/monitoring')
code('sudo tee /opt/monitoring/health-check.sh << \'SCRIPT\'')
code('#!/bin/bash')
code('while true; do')
code('    LOAD=$(cat /proc/loadavg | cut -d" " -f1)')
code('    MEM=$(free -m | awk "/Mem:/{print $4}")')
code('    echo "$(date) | load=$LOAD | mem_free=${MEM}MB"')
code('    sleep 60')
code('done')
code('SCRIPT')
code('sudo chmod +x /opt/monitoring/health-check.sh')
code('')
code('# Create the unit file')
code('sudo tee /etc/systemd/system/health-monitor.service << \'UNIT\'')
code('[Unit]')
code('Description=System Health Monitor')
code('After=network.target')
code('')
code('[Service]')
code('Type=simple')
code('ExecStart=/opt/monitoring/health-check.sh')
code('Restart=on-failure')
code('RestartSec=10')
code('StandardOutput=journal')
code('StandardError=journal')
code('NoNewPrivileges=true')
code('ProtectSystem=strict')
code('ProtectHome=true')
code('')
code('[Install]')
code('WantedBy=multi-user.target')
code('UNIT')
code('')
code('# Load, enable, start')
code('sudo systemctl daemon-reload')
code('sudo systemctl enable --now health-monitor')
code('sudo systemctl status health-monitor')
code('sudo journalctl -u health-monitor -n 10')
code('sudo journalctl -u health-monitor -f    # Follow live (Ctrl+C)')

doc.add_paragraph()
bold_body('Key commands — memorize:', '')
code('systemctl start/stop/restart/status SERVICE')
code('systemctl enable/disable SERVICE')
code('systemctl enable --now SERVICE    # Start + boot persist')
code('systemctl daemon-reload           # After editing unit files')
code('systemctl is-active SERVICE')

doc.add_paragraph()
bold_body('Unit file sections:', '')
bullet('[Unit] = Description + After (dependency ordering)', '')
bullet('[Service] = ExecStart (command), Restart (on-failure/always), User, security hardening', '')
bullet('[Install] = WantedBy=multi-user.target (normal boot)', '')

doc.add_paragraph()
bold_body('Interview:', '')
bullet('"systemctl status shows state + last log lines. journalctl -u service -n 50 for details. Exit code 137 = OOM killed. Permission denied = wrong User in unit file."', 'Q: Service keeps crashing, how to troubleshoot? ')
bullet('"daemon-reload re-reads unit files from disk. Without it, systemd uses the old cached version."', 'Q: What does daemon-reload do? ')
bullet('"start = run now. enable = start on boot. Independent — can start without enabling. enable --now does both."', 'Q: enable vs start? ')

doc.add_paragraph()

doc.add_heading('Block 2: Cron Jobs (15 min)', level=2)

bold_body('Do this:', '')
code('# Cron format:')
code('# min  hour  day  month  weekday  command')
code('# 0    2     *    *      *        /script.sh    = Daily 2 AM')
code('# */15 *     *    *      *        /check.sh     = Every 15 min')
code('# 0    0     *    *      0        /weekly.sh    = Sunday midnight')
code('')
code('# Create a backup script')
code('sudo tee /opt/monitoring/backup.sh << \'SCRIPT\'')
code('#!/bin/bash')
code('DATE=$(date +%Y%m%d-%H%M)')
code('mkdir -p /opt/backups')
code('tar -czf /opt/backups/configs-$DATE.tar.gz /etc/ssh/sshd_config /etc/fstab 2>/dev/null')
code('find /opt/backups -name "*.tar.gz" -mtime +7 -delete')
code('echo "$(date) Backup done" >> /opt/backups/backup.log')
code('SCRIPT')
code('sudo chmod +x /opt/monitoring/backup.sh')
code('')
code('# Add cron job')
code('(sudo crontab -l 2>/dev/null; echo "0 2 * * * /opt/monitoring/backup.sh") | sudo crontab -')
code('sudo crontab -l    # Verify')
code('')
code('# Test manually')
code('sudo /opt/monitoring/backup.sh')
code('ls -la /opt/backups/')

doc.add_paragraph()
bold_body('Interview:', '')
bullet('"crontab -e, add 0 2 * * * /path/to/script.sh. Always test manually first, redirect output to a log."', 'Q: Schedule a task at 2 AM daily? ')
bullet('"Cron for simple time-based. systemd timers for journalctl integration, dependency ordering, and Persistent=true (runs missed jobs)."', 'Q: Cron vs systemd timers? ')

doc.add_paragraph()

doc.add_heading('Block 3: Log Analysis (20 min)', level=2)

bold_body('Do this:', '')
code('# journalctl basics')
code('journalctl -n 20                          # Last 20 lines')
code('journalctl --since "1 hour ago"')
code('journalctl -u ssh                         # SSH service only')
code('journalctl -u health-monitor -f           # Follow your service')
code('journalctl -p err                         # Errors only')
code('journalctl --disk-usage                   # Storage used')
code('')
code('# grep patterns')
code('grep "Failed password" /var/log/auth.log 2>/dev/null')
code('grep -c "Failed" /var/log/auth.log 2>/dev/null    # Count')
code('grep -i "error" /var/log/syslog 2>/dev/null | head')
code('')
code('# SOC analysis — combine them')
code('journalctl -u ssh --since today | grep "Failed password" | \\')
code('  grep -oP "\\d+\\.\\d+\\.\\d+\\.\\d+" | sort | uniq -c | sort -rn | head -5')
code('# ^ Top 5 IPs failing SSH login')
code('')
code('journalctl --since today | grep "sudo" | grep "COMMAND"    # Who used sudo')

doc.add_paragraph()
bold_body('Interview:', '')
bullet('"journalctl -u ssh --since 1h ago | grep Failed to see volume. Extract IPs with grep + sort + uniq -c. Check grep Accepted for successful breach. Then last for sessions, sudo logs for what they did."', 'Q: Investigate SSH brute-force? ')

doc.add_paragraph()

doc.add_heading('Block 4: LVM + fstab (30 min)', level=2)
bold_body('If you have an extra virtual disk (recommended): ', 'Add a 5GB disk to your VM.')
doc.add_paragraph()

bold_body('Do this:', '')
code('# The LVM hierarchy:')
code('# Physical Disk → PV → VG (pool) → LV (flexible partition) → filesystem → mount')
code('')
code('sudo pvcreate /dev/sdb')
code('sudo pvs')
code('')
code('sudo vgcreate vg_data /dev/sdb')
code('sudo vgs')
code('')
code('sudo lvcreate -L 2G -n lv_logs vg_data')
code('sudo lvcreate -L 1G -n lv_appdata vg_data')
code('sudo lvs')
code('')
code('sudo mkfs.ext4 /dev/vg_data/lv_logs')
code('sudo mkfs.ext4 /dev/vg_data/lv_appdata')
code('')
code('sudo mkdir -p /opt/company/logs /opt/company/appdata')
code('sudo mount /dev/vg_data/lv_logs /opt/company/logs')
code('sudo mount /dev/vg_data/lv_appdata /opt/company/appdata')
code('df -h /opt/company/logs /opt/company/appdata')
code('')
code('# THE KEY SKILL — live expansion')
code('sudo lvextend -L +1G /dev/vg_data/lv_logs')
code('sudo resize2fs /dev/vg_data/lv_logs')
code('df -h /opt/company/logs    # Now 3GB, zero downtime!')
code('')
code('# fstab — persist across reboots')
code('sudo cp /etc/fstab /etc/fstab.backup')
code('echo "/dev/vg_data/lv_logs /opt/company/logs ext4 defaults,noexec,nosuid 0 2" | sudo tee -a /etc/fstab')
code('sudo umount /opt/company/logs')
code('sudo mount -a    # Test fstab')
code('df -h /opt/company/logs    # Verify')

doc.add_paragraph()
bold_body('Interview:', '')
bullet('"PV (raw disks) → VG (pool them) → LV (flexible partitions) → mkfs → mount"', 'Q: LVM hierarchy? ')
bullet('"Check vgs for free space. lvextend -L +5G /dev/vg/lv, resize2fs — done live, no unmount."', 'Q: /var/log full on LVM? ')
bullet('"noexec prevents executing binaries from that mount. Even if attacker writes malware to logs, kernel won\'t execute it."', 'Q: Why noexec on logs? ')
bullet('"Device, mount point, fstype, options, dump, fsck. Always backup first. Test with mount -a before rebooting."', 'Q: What is fstab? ')

doc.add_page_break()

# ============================================================================
# DAY 3
# ============================================================================
doc.add_heading('DAY 3: iptables Firewall + SSH Security', level=1)
bold_body('Resume claim this proves: ', '"Configured iptables firewall rules to control inbound and outbound traffic and verified them by testing with live traffic"')
doc.add_paragraph()

doc.add_heading('Block 1: iptables — Build a Firewall (45 min)', level=2)

bold_body('Do this:', '')
code('# View current rules')
code('sudo iptables -L -n -v')
code('')
code('# Flush and start clean')
code('sudo iptables -F')
code('sudo iptables -X')
code('')
code('# DEFAULT DENY — block everything incoming')
code('sudo iptables -P INPUT DROP')
code('sudo iptables -P FORWARD DROP')
code('sudo iptables -P OUTPUT ACCEPT')
code('')
code('# Rule 1: Allow loopback (localhost)')
code('sudo iptables -A INPUT -i lo -j ACCEPT')
code('')
code('# Rule 2: Allow established connections (responses to OUR requests)')
code('sudo iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT')
code('')
code('# Rule 3: Allow SSH')
code('sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT')
code('')
code('# Rule 4: Allow HTTP/HTTPS')
code('sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT')
code('sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT')
code('')
code('# Rule 5: Allow ping')
code('sudo iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT')
code('')
code('# Rule 6: Log everything else before dropping')
code('sudo iptables -A INPUT -j LOG --log-prefix "DROPPED: " --log-level 4')
code('')
code('# View final ruleset')
code('sudo iptables -L -n -v --line-numbers')
code('')
code('# TEST WITH LIVE TRAFFIC (as resume claims)')
code('curl http://localhost    # Should work (port 80 allowed)')
code('# From another machine: try connecting to a blocked port')
code('# Check logs: sudo journalctl -k | grep DROPPED')
code('')
code('# Rate limiting for SSH (brute-force defense)')
code('sudo iptables -D INPUT -p tcp --dport 22 -j ACCEPT    # Remove simple rule')
code('sudo iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --set --name SSH')
code('sudo iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 4 --name SSH -j LOG --log-prefix "SSH-BRUTE: "')
code('sudo iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 4 --name SSH -j DROP')
code('sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT')
code('')
code('# Save rules to persist across reboots')
code('sudo apt install iptables-persistent -y')
code('sudo netfilter-persistent save')
code('')
code('# Final verify')
code('sudo iptables -L -n -v --line-numbers')

doc.add_paragraph()
bold_body('Interview answers:', '')
bullet('"Default DROP on INPUT — block everything. Whitelist: loopback, ESTABLISHED/RELATED, SSH with rate limiting, HTTP/HTTPS, ICMP. Log before implicit drop. Persist with iptables-persistent."', 'Q: Walk through your firewall? ')
bullet('"Responses to our outbound requests. Without it, DNS replies and apt updates get dropped."', 'Q: What\'s ESTABLISHED,RELATED? ')
bullet('"recent module tracks connections per IP. >3 new SSH in 60 seconds → LOG + DROP. Legit users connect once. Brute-force tools try hundreds."', 'Q: How does rate limiting work? ')

doc.add_paragraph()

doc.add_heading('Block 2: SSH Security (35 min)', level=2)

bold_body('Do this:', '')
code('# Generate keys')
code('ssh-keygen -t ed25519 -C "lab-key" -f ~/.ssh/lab_key')
code('ls -la ~/.ssh/lab_key*')
code('chmod 700 ~/.ssh')
code('chmod 600 ~/.ssh/lab_key')
code('chmod 644 ~/.ssh/lab_key.pub')
code('')
code('# Deploy key')
code('ssh-copy-id -i ~/.ssh/lab_key.pub localhost')
code('ssh -i ~/.ssh/lab_key localhost whoami    # No password prompt!')
code('')
code('# Harden SSH daemon')
code('sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup')
code('sudo tee /etc/ssh/sshd_config.d/hardening.conf << \'SSH\'')
code('PasswordAuthentication no')
code('PermitRootLogin no')
code('MaxAuthTries 3')
code('PermitEmptyPasswords no')
code('ClientAliveInterval 300')
code('ClientAliveCountMax 2')
code('X11Forwarding no')
code('LogLevel VERBOSE')
code('SSH')
code('')
code('sudo sshd -t    # Test config (no output = valid)')
code('sudo systemctl restart sshd')
code('sudo sshd -T | grep -E "passwordauthentication|permitrootlogin"')
code('')
code('# SCP file transfer')
code('echo "test" > ~/testfile.txt')
code('scp -i ~/.ssh/lab_key ~/testfile.txt localhost:/tmp/')
code('scp -i ~/.ssh/lab_key localhost:/etc/hostname ~/remote-hostname.txt')

doc.add_paragraph()
bold_body('Interview answers:', '')
bullet('"Keys use asymmetric crypto — private key never crosses the network. Can\'t be brute-forced, phished, or guessed. With PasswordAuthentication no, brute-force is structurally impossible."', 'Q: Why keys over passwords? ')
bullet('"Forces named user accounts + sudo. Creates audit trail — I see alice ran sudo apt install vs anonymous root did something."', 'Q: Why PermitRootLogin no? ')
bullet('"Console access — hypervisor console or cloud serial console. That\'s why I always keep an existing session open while testing, run sshd -t first, and confirm key auth works before disabling passwords."', 'Q: Locked yourself out? ')

doc.add_paragraph()

bold_body('STAR — "How did you secure remote access?":', '')
p = doc.add_paragraph()
r = p.add_run('Situation: Server needed SSH but zero-tolerance for credential breaches. Task: Make password attacks structurally impossible. Action: ed25519 key auth, PasswordAuthentication no, PermitRootLogin no, MaxAuthTries 3, idle timeouts. iptables rate-limits SSH to 3/min per IP. Result: No password to guess = brute-force impossible. Rate limiting blocks scanners. Every auth attempt logged for SOC visibility.')
r.italic = True

doc.add_page_break()

# ============================================================================
# DAY 4
# ============================================================================
doc.add_heading('DAY 4: Docker — Images, Containers, Volumes, Networks', level=1)
bold_body('Resume claim this proves: ', '"Containerized the full stack with Docker" + "container networking and volume persistence"')
doc.add_paragraph()

doc.add_heading('Block 1: Dockerfile (30 min)', level=2)

bold_body('Do this:', '')
code('mkdir -p ~/docker-lab && cd ~/docker-lab')
code('')
code('# Create a Flask app')
code('cat > app.py << \'PY\'')
code('from flask import Flask, jsonify')
code('import os, datetime')
code('app = Flask(__name__)')
code('@app.route("/health")')
code('def health():')
code('    return jsonify({"status": "ok", "host": os.uname().nodename,')
code('                    "time": datetime.datetime.now().isoformat()})')
code('@app.route("/")')
code('def home():')
code('    return jsonify({"app": "AI-SOC Watchdog", "version": "1.0"})')
code('if __name__ == "__main__":')
code('    app.run(host="0.0.0.0", port=5000)')
code('PY')
code('')
code('echo "flask==3.0.0" > requirements.txt')
code('echo "gunicorn==21.2.0" >> requirements.txt')
code('')
code('cat > Dockerfile << \'DF\'')
code('FROM python:3.11-slim')
code('WORKDIR /app')
code('COPY requirements.txt .')
code('RUN pip install --no-cache-dir -r requirements.txt')
code('COPY app.py .')
code('RUN useradd -r -s /usr/sbin/nologin appuser')
code('USER appuser')
code('EXPOSE 5000')
code('ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "app:app"]')
code('DF')
code('')
code('docker build -t alert-api:v1 .')
code('docker images alert-api')
code('docker history alert-api:v1    # See layers')

doc.add_paragraph()
bold_body('Key instructions — know cold:', '')
bullet('FROM = base image (use slim/alpine). WORKDIR = set directory.', '')
bullet('COPY requirements FIRST → RUN pip install → COPY code (layer cache optimization)', '')
bullet('USER = non-root (security). EXPOSE = documentation. ENTRYPOINT = startup command.', '')
bullet('ENTRYPOINT = fixed command. CMD = overridable default args.', '')
bullet('COPY is simple + explicit. ADD can fetch URLs + extract tars. Prefer COPY.', '')

doc.add_paragraph()

doc.add_heading('Block 2: Container Lifecycle (25 min)', level=2)

bold_body('Do this:', '')
code('# Run')
code('docker run -d --name my-api -p 5000:5000 alert-api:v1')
code('curl http://localhost:5000/health')
code('')
code('# Inspect')
code('docker ps                              # Running containers')
code('docker ps -a                           # ALL including stopped')
code('docker logs my-api                     # App output')
code('docker logs my-api --tail 20           # Last 20 lines')
code('docker logs -f my-api                  # Follow live')
code('docker exec my-api cat /etc/os-release # Command inside')
code('docker exec -it my-api /bin/bash       # Interactive shell')
code('docker stats my-api                    # Live CPU/memory')
code('docker inspect my-api | grep -i ipaddress')
code('')
code('# Lifecycle')
code('docker stop my-api')
code('docker start my-api')
code('docker restart my-api')
code('docker stop my-api && docker rm my-api')

doc.add_paragraph()
bold_body('Interview:', '')
bullet('"docker logs for output. docker ps -a for exit code — 137=OOM, 1=app error. docker inspect for full details. docker run -it image /bin/sh to debug interactively."', 'Q: Container crashed, how to debug? ')

doc.add_paragraph()

doc.add_heading('Block 3: Volumes + Networks (30 min)', level=2)

bold_body('Do this:', '')
code('# VOLUMES — data persistence')
code('docker volume create app-data')
code('docker volume ls')
code('docker volume inspect app-data')
code('')
code('docker run -d --name my-api -p 5000:5000 -v app-data:/app/data alert-api:v1')
code('docker rm -f my-api')
code('docker volume ls    # Volume survives!')
code('')
code('# Bind mount')
code('mkdir -p ~/app-logs')
code('docker run -d --name my-api -p 5000:5000 -v ~/app-logs:/app/logs alert-api:v1')
code('')
code('# NETWORKS — container communication')
code('docker network create app-network')
code('docker run -d --name my-api --network app-network -p 5000:5000 alert-api:v1')
code('docker run --rm --network app-network alpine ping -c 2 my-api    # DNS works!')
code('')
code('# Network isolation')
code('docker network create isolated-net')
code('docker run -d --name isolated --network isolated-net alpine sleep infinity')
code('docker exec isolated ping -c 2 my-api 2>&1    # FAILS — different networks')
code('')
code('# Cleanup')
code('docker rm -f my-api isolated')
code('docker network rm app-network isolated-net')
code('docker volume rm app-data')

doc.add_paragraph()
bold_body('Interview:', '')
bullet('"Named volumes = Docker-managed, survive container removal. Bind mounts = host directory mapped into container. Volumes for databases/state, bind mounts for configs/logs/dev code."', 'Q: Volume vs bind mount? ')
bullet('"Custom bridge provides DNS — containers find each other by name. Default bridge = IP only. Custom networks also provide isolation between unrelated services."', 'Q: Why custom networks? ')

doc.add_page_break()

# ============================================================================
# DAY 5
# ============================================================================
doc.add_heading('DAY 5: Docker Compose + AI-SOC Watchdog + JD Concepts', level=1)
bold_body('Resume claims this proves: ', '"Used Docker Compose to run multi-service applications" + "Deployed infrastructure on AWS using Terraform" + "Configured S3 bucket as database fallback"')
doc.add_paragraph()

doc.add_heading('Block 1: Docker Compose — Full Stack (45 min)', level=2)

bold_body('Do this:', '')
code('mkdir -p ~/compose-lab/{app,nginx} && cd ~/compose-lab')
code('')
code('# Copy app files from Day 4')
code('cp ~/docker-lab/* app/')
code('')
code('# Nginx config')
code('cat > nginx/default.conf << \'CONF\'')
code('upstream api { server alert-api:5000; }')
code('server {')
code('    listen 80;')
code('    location / {')
code('        proxy_pass http://api;')
code('        proxy_set_header Host $host;')
code('        proxy_set_header X-Real-IP $remote_addr;')
code('    }')
code('}')
code('CONF')
code('')
code('# docker-compose.yml')
code('cat > docker-compose.yml << \'YML\'')
code('version: "3.8"')
code('services:')
code('  nginx:')
code('    image: nginx:alpine')
code('    container_name: proxy')
code('    ports: ["80:80"]')
code('    volumes:')
code('      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro')
code('    networks: [frontend]')
code('    depends_on: [alert-api]')
code('    restart: unless-stopped')
code('')
code('  alert-api:')
code('    build: ./app')
code('    container_name: api')
code('    environment:')
code('      - FLASK_ENV=production')
code('    volumes:')
code('      - api-logs:/app/logs')
code('    networks: [frontend, backend]')
code('    restart: unless-stopped')
code('')
code('  redis:')
code('    image: redis:7-alpine')
code('    container_name: datastore')
code('    command: redis-server --appendonly yes')
code('    volumes:')
code('      - redis-data:/data')
code('    networks: [backend]')
code('    restart: unless-stopped')
code('')
code('networks:')
code('  frontend:')
code('  backend:')
code('    internal: true')
code('')
code('volumes:')
code('  api-logs:')
code('  redis-data:')
code('YML')
code('')
code('# Start')
code('docker compose up -d --build')
code('docker compose ps')
code('curl http://localhost/health')
code('')
code('# VERIFY NETWORK ISOLATION (critical for interview)')
code('docker exec proxy ping -c 2 datastore 2>&1    # FAILS!')
code('docker exec api ping -c 2 datastore            # WORKS')
code('')
code('# VERIFY PERSISTENCE')
code('docker compose down')
code('docker compose up -d')
code('docker volume ls | grep redis    # Volume survived')
code('')
code('# Management commands')
code('docker compose logs -f alert-api    # Follow one service')
code('docker compose exec api sh          # Shell into service')
code('docker compose down                 # Stop (keep volumes)')
code('# docker compose down -v            # DESTRUCTIVE — deletes data')

doc.add_paragraph()
bold_body('Interview answers:', '')
bullet('"Declarative YAML defining services, networks, and volumes. One command starts the entire stack. Version-controlled, reproducible, self-documenting."', 'Q: What is Docker Compose? ')
bullet('"internal: true removes the gateway — no external access. Redis only exists on the backend network. Even port scanning the host can\'t find it. Only the API, bridging both networks, can reach it."', 'Q: Why internal: true? ')
bullet('"down keeps volumes (data safe). down -v DELETES volumes = permanent data loss. Never run -v in production accidentally."', 'Q: down vs down -v? ')
bullet('"Controls startup ORDER only, not readiness. Redis container starts before API, but Redis might still be initializing. Use healthchecks with condition: service_healthy for true readiness."', 'Q: depends_on limitation? ')

doc.add_paragraph()

bold_body('STAR — "Walk through your container architecture":', '')
p = doc.add_paragraph()
r = p.add_run('Situation: Deploying a security alert tool with 3 components — proxy, API, data store. Redis exposure would leak threat intel. Task: Deploy with network segmentation and persistence. Action: Docker Compose with frontend + backend (internal: true) networks. Redis has no port mappings, exists only on isolated backend. Named volumes persist Redis data across restarts. All services restart unless-stopped. Result: nginx cannot ping Redis (different networks). Data survives compose down/up. Entire architecture in one auditable YAML file.')
r.italic = True

doc.add_paragraph()

doc.add_heading('Block 2: AI-SOC Watchdog Deployment Knowledge (30 min READ)', level=2)
bold_body('Your resume says "Deployed infrastructure on AWS using Terraform" and "Configured S3 as database fallback." Be ready to explain:', '')
doc.add_paragraph()

blue_label('S3 Failover (you already built this):')
bullet('Normal mode: reads/writes go to Supabase, background sync to S3 every 5 min')
bullet('Failover mode: after 3 consecutive DB failures, reads fall back to S3 automatically')
bullet('Recovery: when Supabase recovers, system auto-exits failover mode')
bullet('Limitation: writes during failover need manual reconciliation')
bullet('"I configured S3 as a database fallback using boto3. The system detects 3 consecutive Supabase failures, switches to reading from S3, and auto-recovers when the DB comes back."', 'Interview answer: ')

doc.add_paragraph()
blue_label('Environment Variables & Security (you already built this):')
bullet('All secrets in .env: ANTHROPIC_API_KEY, SUPABASE_KEY, SESSION_SECRET, INGEST_API_KEY')
bullet('python-dotenv loads them; never committed to git (.gitignore)')
bullet('Request validation: Pydantic schema validation on all inputs')
bullet('Authentication: session-based login with secrets.compare_digest() (timing-safe)')
bullet('2MB request size limit, secure cookies, header redaction in logs')

doc.add_paragraph()
blue_label('Terraform (conceptual — know what you\'d provision):')
bullet('VPC with public/private subnets')
bullet('EC2 or ECS/EKS for the containerized backend')
bullet('RDS PostgreSQL (or keep Supabase)')
bullet('S3 bucket for failover')
bullet('ALB for load balancing')
bullet('IAM roles for least-privilege access')
bullet('Security groups as virtual firewalls')

doc.add_paragraph()

doc.add_heading('Block 3: JD Concepts — Kubernetes + CI/CD (30 min READ)', level=2)
bold_body('The JD wants foundational understanding. You don\'t need hands-on K8s — just know what it is and how your project would use it.', '')
doc.add_paragraph()

blue_label('Kubernetes / EKS (conceptual):')
bullet('Pod = smallest unit, runs 1+ containers. Your Flask API = 1 pod.', 'Pod: ')
bullet('Deployment = manages replicas. "Run 2 copies of my API, restart if one dies."', 'Deployment: ')
bullet('Service = stable internal endpoint. "api-service:5000" always routes to healthy pods.', 'Service: ')
bullet('Ingress = external traffic entry point. Like nginx in your Compose, but K8s-native.', 'Ingress: ')
bullet('ConfigMap = non-sensitive config. Secret = sensitive data (API keys).', 'ConfigMap/Secret: ')
bullet('PersistentVolumeClaim = volume in K8s. Like your docker volumes but cloud-backed (EBS).', 'PVC: ')
bullet('"Kubernetes is container orchestration at scale. My Docker Compose works for a single server. If I need 10 replicas across multiple servers with auto-scaling, health-check-based restarts, and rolling updates — that\'s what K8s does. EKS is AWS-managed K8s so I don\'t manage the control plane."', 'Interview answer: ')

doc.add_paragraph()
blue_label('CI/CD with GitHub Actions:')
bullet('Trigger: on push to main')
bullet('Step 1: Run tests (python tests/run_all_tests.py --quick)')
bullet('Step 2: Build Docker image')
bullet('Step 3: Push to container registry (ECR or Docker Hub)')
bullet('Step 4: Deploy (kubectl apply or docker compose up on the server)')
bullet('Step 5: Health check (curl /health)')
bullet('"Push to main triggers GitHub Actions: run tests, build Docker image, push to registry, deploy to the server, and verify with a health check. Staging branch deploys to staging, main to production."', 'Interview answer: ')

doc.add_paragraph()
blue_label('Terraform IaC:')
bullet('"Infrastructure as Code means I define cloud resources in .tf files. I can version-control it, review changes in PRs, and terraform apply to create or update. terraform destroy tears it all down. It\'s reproducible — I can rebuild the entire environment from scratch in minutes."', 'Interview answer: ')

doc.add_paragraph()
blue_label('Service Mesh (Istio) — just know the concept:')
bullet('"A service mesh adds a sidecar proxy to every pod that handles service-to-service communication — mTLS encryption, traffic routing, retries, and observability. Istio is the most common. I haven\'t implemented it but I understand it adds a security and observability layer between microservices."', 'Interview answer: ')

doc.add_page_break()

# ============================================================================
# CHEAT SHEET
# ============================================================================
doc.add_heading('One-Page Cheat Sheet — Print This', level=1)

doc.add_heading('Linux', level=2)
code('useradd -m -s /bin/bash USER          # Human user')
code('useradd -r -s /usr/sbin/nologin SVC   # Service account')
code('usermod -aG GROUP USER                # Add to group (ALWAYS -a)')
code('chmod 770 DIR / chmod 2770 DIR        # Team access / SGID')
code('systemctl enable --now SERVICE        # Start + boot persist')
code('systemctl status SERVICE              # Check status')
code('journalctl -u SERVICE -n 20           # Service logs')
code('journalctl -p err --since "1h ago"    # Recent errors')
code('pvcreate → vgcreate → lvcreate → mkfs → mount')
code('lvextend -L +5G LV && resize2fs LV   # Live expand')
code('iptables -P INPUT DROP               # Default deny')
code('iptables -A INPUT -p tcp --dport 22 -j ACCEPT')
code('ssh-keygen -t ed25519                 # Generate key')
code('PasswordAuthentication no             # SSH hardening')

doc.add_heading('Docker', level=2)
code('docker build -t name:tag .            # Build image')
code('docker run -d --name X -p 80:80 IMG   # Run container')
code('docker ps / logs / exec / stop / rm   # Lifecycle')
code('docker volume create NAME             # Persistent storage')
code('docker network create NAME            # Custom network w/ DNS')

doc.add_heading('Docker Compose', level=2)
code('docker compose up -d --build          # Start stack')
code('docker compose ps / logs / down       # Manage')
code('internal: true                        # Isolate network')
code('docker compose down -v                # DESTRUCTIVE')

doc.add_heading('JD Concepts (Verbal)', level=2)
code('K8s: Pod → Deployment → Service → Ingress')
code('Terraform: terraform init/plan/apply/destroy')
code('CI/CD: push → test → build → push image → deploy → health check')
code('Service Mesh: sidecar proxies for mTLS, routing, observability')

doc.add_page_break()

# ============================================================================
# DAILY SCHEDULE
# ============================================================================
doc.add_heading('Exact Daily Schedule', level=1)

doc.add_heading('Day 1 (Today) — Linux Identity & Access', level=2)
bullet('Filesystem hierarchy — ls the key directories, know what lives where', '0:00-0:15 → ')
bullet('User management — create human user, service account, modify groups', '0:15-0:40 → ')
bullet('Group management — create team groups, assign users', '0:40-0:55 → ')
bullet('Permissions — chmod/chown/SGID/sticky, test access control, memorize interview answers', '0:55-1:25 → ')
bullet('Review — explain users, groups, permissions, SUID, SGID without notes', '1:25-1:35 → ')
bullet('Read the STAR answer, practice saying it once out loud', '1:35-2:00 → ')

doc.add_heading('Day 2 — Linux Operations & Storage', level=2)
bullet('systemd — create health monitor service, learn lifecycle commands', '0:00-0:35 → ')
bullet('Cron — create one backup cron job, test it', '0:35-0:50 → ')
bullet('Log analysis — journalctl + grep patterns, SOC analysis combo', '0:50-1:10 → ')
bullet('LVM — create PV/VG/LV, mount, EXPAND LIVE, configure fstab', '1:10-1:40 → ')
bullet('Review — explain systemd, cron format, LVM hierarchy, fstab without notes', '1:40-2:00 → ')

doc.add_heading('Day 3 — Linux Security', level=2)
bullet('iptables — build firewall from scratch, default deny, whitelist rules', '0:00-0:45 → ')
bullet('Rate limiting — replace simple SSH rule with rate-limited version', '0:45-1:00 → ')
bullet('SSH keys — generate, deploy, test passwordless login', '1:00-1:20 → ')
bullet('SSH hardening — apply config, test, verify', '1:20-1:40 → ')
bullet('SCP — transfer files', '1:40-1:50 → ')
bullet('Review — explain your firewall rule by rule, SSH security rationale', '1:50-2:00 → ')

doc.add_heading('Day 4 — Docker', level=2)
bullet('Dockerfile — write, build, understand layers + caching', '0:00-0:30 → ')
bullet('Container lifecycle — run, ps, logs, exec, stop, rm, stats', '0:30-0:55 → ')
bullet('Volumes — named volume + bind mount, prove persistence', '0:55-1:15 → ')
bullet('Networks — custom bridge with DNS, prove isolation between networks', '1:15-1:35 → ')
bullet('Review — explain Dockerfile line by line, ENTRYPOINT vs CMD, volume vs bind mount', '1:35-2:00 → ')

doc.add_heading('Day 5 — Docker Compose + JD Concepts', level=2)
bullet('Docker Compose — build 3-service stack (nginx + api + redis), verify network isolation + persistence', '0:00-0:45 → ')
bullet('AI-SOC Watchdog knowledge — S3 failover, env vars, Terraform concepts', '0:45-1:15 → ')
bullet('JD concepts — read K8s, CI/CD, Terraform, service mesh interview answers', '1:15-1:45 → ')
bullet('FINAL TEST: pick 5 random concepts, explain each in 30 seconds. Pick 2 STAR answers, say them out loud.', '1:45-2:00 → ')

doc.add_paragraph()
doc.add_paragraph()
green_text('After Day 5: You can back up every resume claim with hands-on proof and interview answers.')

# Save
output_path = r'c:\Users\karan\Desktop\5Day_Linux_Docker_Plan.docx'
doc.save(output_path)
print(f"Saved to: {output_path}")
